pipeline {
    agent any

    tools {
        jdk 'jdk21' 
    }

    environment {
        DOCKER_PASSWORD = credentials("DockerPass")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
    }
}
