pipeline {
    agent any

    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }
    environment {
        DOCKER_PASSWORD = credentials("docker_pass2")
        GITHUB_TOKEN = credentials("git_token22")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh 'git fetch --tag'
                    def GIT_TAG = sh(script: 'git tag | sort --version-sort | tail -1', returnStdout: true).trim()
                    def MAJOR_VERSION = GIT_TAG.split('\\.')[0]
                    def MINOR_VERSION = GIT_TAG.split('\\.')[1].toInteger()
                    def PATCH_VERSION = GIT_TAG.split('\\.')[2]
                    def IMAGE_TAG = "${MAJOR_VERSION}.${MINOR_VERSION + 1}.${PATCH_VERSION}"

                    sh "docker build -t bogdancomardici/hello-img:${IMAGE_TAG} ."
                    sh "echo ${DOCKER_PASSWORD} | docker login -u bogdancomardici --password-stdin"
                    sh "docker push bogdancomardici/hello-img:${IMAGE_TAG}"

                    sh "git tag ${IMAGE_TAG}"
                    sh "git push https://${GITHUB_TOKEN}@github.com/bogdancomardici/service.git ${IMAGE_TAG}"
                }
            }
        }

        stage('Docker Compose') {
            steps {
                script {
                    sh '''
                        #!/bin/bash
                        IMAGE_TAG=${IMAGE_TAG}
                        docker compose up -d hello mongo
                    '''
                }
            }
        }
    }
}
